# Generated by Django 6.0.7 on 2026-07-11 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empilhadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('setor', models.CharField(blank=True, max_length=80)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empilhadeira',
                'verbose_name_plural': 'empilhadeiras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('descricao', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=10)),
                ('aberta_em', models.DateField(default=django.utils.timezone.localdate)),
                ('fechada_em', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['status', '-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('turno', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('tempo', 'Tempo'), ('produto', 'Produto'), ('avaria', 'Avaria'), ('retrabalho', 'Retrabalho'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=180)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('impacto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acao_corretiva', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'perda',
                'verbose_name_plural': 'perdas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ReuniaoGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tema', models.CharField(max_length=140)),
                ('participantes', models.TextField(blank=True)),
                ('pauta', models.TextField(blank=True)),
                ('decisoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'reuniao de GA',
                'verbose_name_plural': 'reunioes de GA',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('expedicao', 'Expedicao'), ('abastecimento', 'Abastecimento'), ('transferencia', 'Transferencia'), ('outro', 'Outro')], max_length=20)),
                ('origem', models.CharField(max_length=80)),
                ('destino', models.CharField(max_length=80)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacao', models.TextField(blank=True)),
                ('empilhadeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.empilhadeira')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador')),
            ],
            options={
                'verbose_name': 'movimentacao',
                'verbose_name_plural': 'movimentacoes',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LimpezaEmpilhadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('limpeza_externa', models.BooleanField(default=False)),
                ('limpeza_interna', models.BooleanField(default=False)),
                ('bateria_ou_combustivel', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('empilhadeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.empilhadeira')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador')),
            ],
            options={
                'verbose_name': 'limpeza de empilhadeira',
                'verbose_name_plural': 'limpezas de empilhadeiras',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('item_verificado', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('atencao', 'Atencao'), ('critico', 'Critico')], default='ok', max_length=10)),
                ('acao_tomada', models.TextField(blank=True)),
                ('empilhadeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.empilhadeira')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador')),
            ],
            options={
                'verbose_name': 'registro de seguranca',
                'verbose_name_plural': 'registros de seguranca',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AcaoReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('responsavel', models.CharField(max_length=120)),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluida'), ('atrasada', 'Atrasada')], default='pendente', max_length=20)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='operacoes.reuniaoga')),
            ],
            options={
                'verbose_name': 'acao de reuniao',
                'verbose_name_plural': 'acoes de reuniao',
                'ordering': ['prazo'],
            },
        ),
    ]
