# Generated by Django 6.0.7 on 2026-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='operador',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='perda',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='reuniaoga',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
    ]
