# Generated by Django 6.0.7 on 2026-07-11 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_etiqueta_equipe_operador_equipe_perda_equipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_hora'], 'verbose_name': 'perda de movimentacao', 'verbose_name_plural': 'perdas de movimentacao'},
        ),
        migrations.AlterModelOptions(
            name='registroseguranca',
            options={'ordering': ['-data_hora'], 'verbose_name': 'ocorrencia de seguranca', 'verbose_name_plural': 'ocorrencias de seguranca'},
        ),
        migrations.RemoveField(
            model_name='limpezaempilhadeira',
            name='bateria_ou_combustivel',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='registroseguranca',
            name='data',
        ),
        migrations.AddField(
            model_name='empilhadeira',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='custo_reais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='motivo',
            field=models.CharField(default='Nao informado', max_length=180),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tempo_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perda',
            name='movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdas', to='operacoes.movimentacao'),
        ),
        migrations.AddField(
            model_name='perda',
            name='seguranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdas', to='operacoes.registroseguranca'),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='foto',
            field=models.FileField(blank=True, upload_to='seguranca/'),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='motivo',
            field=models.CharField(default='Nao informado', max_length=180),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('tempo', 'Tempo'), ('custo', 'Custo em reais'), ('avaria', 'Avaria'), ('retrabalho', 'Retrabalho'), ('outro', 'Outro')], max_length=20, verbose_name='tipo de perda'),
        ),
        migrations.AlterField(
            model_name='registroseguranca',
            name='item_verificado',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
