# Generated by Django 6.0.7 on 2026-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_alter_movimentacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoreuniao',
            name='reuniao',
        ),
        migrations.RemoveField(
            model_name='limpezaempilhadeira',
            name='empilhadeira',
        ),
        migrations.RemoveField(
            model_name='limpezaempilhadeira',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='empilhadeira',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='movimentacao',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='seguranca',
        ),
        migrations.RemoveField(
            model_name='registroseguranca',
            name='empilhadeira',
        ),
        migrations.RemoveField(
            model_name='registroseguranca',
            name='operador',
        ),
        migrations.AddField(
            model_name='acaoreuniao',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='acaoreuniao',
            name='reuniao_tema',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='limpezaempilhadeira',
            name='empilhadeira_codigo',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='limpezaempilhadeira',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='limpezaempilhadeira',
            name='responsavel_nome',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='empilhadeira_codigo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='equipe',
            field=models.CharField(choices=[('minha', 'Minha equipe'), ('diego', 'Equipe do Diego')], default='minha', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='operador_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='empilhadeira_codigo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='operador_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
