# Generated by Django 6.0.7 on 2026-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_remove_acaoreuniao_reuniao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoreuniao',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='empilhadeira',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='limpezaempilhadeira',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='impacto_estimado',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='registroseguranca',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='reuniaoga',
            name='equipe',
        ),
        migrations.AddField(
            model_name='perda',
            name='minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perda',
            name='valor_reais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perda',
            name='tipo',
            field=models.CharField(choices=[('minutos', 'Minutos'), ('reais', 'R$')], max_length=20),
        ),
    ]
