# Generated by Django 6.0.7 on 2026-07-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_remove_acaoreuniao_equipe_remove_empilhadeira_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limpezaempilhadeira',
            name='empilhadeira_codigo',
        ),
        migrations.RemoveField(
            model_name='limpezaempilhadeira',
            name='responsavel_nome',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='empilhadeira_codigo',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='operador_nome',
        ),
        migrations.RemoveField(
            model_name='registroseguranca',
            name='empilhadeira_codigo',
        ),
        migrations.RemoveField(
            model_name='registroseguranca',
            name='operador_nome',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador'),
        ),
        migrations.AddField(
            model_name='limpezaempilhadeira',
            name='empilhadeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.empilhadeira'),
        ),
        migrations.AddField(
            model_name='limpezaempilhadeira',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='empilhadeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.empilhadeira'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador'),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='empilhadeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.empilhadeira'),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.operador'),
        ),
    ]
