# Generated by Django 6.0.7 on 2026-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0006_remove_limpezaempilhadeira_empilhadeira_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoreuniao',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
        migrations.AddField(
            model_name='limpezaempilhadeira',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
        migrations.AddField(
            model_name='perda',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
        migrations.AddField(
            model_name='registroseguranca',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
        migrations.AddField(
            model_name='reuniaoga',
            name='responsavel_dashboard',
            field=models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20),
        ),
    ]
