# Generated by Django 6.0.7 on 2026-07-11 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0007_acaoreuniao_responsavel_dashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('responsavel_dashboard', models.CharField(choices=[('ckelyson', 'CKELYSON'), ('diego', 'DIEGO')], default='ckelyson', max_length=20)),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('sugestao', 'Sugestao'), ('andamento', 'Em andamento'), ('implantado', 'Implantado'), ('cancelado', 'Cancelado')], default='sugestao', max_length=20)),
                ('ganho_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'kaizen',
                'verbose_name_plural': 'kaizens',
                'ordering': ['-data'],
            },
        ),
    ]
